release-date = "2023-06-02"

[[entries]]
id = "513479a0-1543-4e58-8f22-08a404b08aa4"
type = "fix"
description = "Fix `Resource.Type.uri()` and `Resource.Locator.uri()` to not be class methods"
author = "@NiklasRosenstein"
