[[entries]]
id = "ce10bbc3-8d63-4e64-b7c0-6eb249de3105"
type = "breaking change"
description = "Rework `Context` class, make it a composite of various registries (i.e. `ControllerRegistry`, `ResourceTypeRegistry`, `ServiceRegistry` and `ResourceRegistry`"
author = "@NiklasRosenstein"

[[entries]]
id = "6a03800f-ec32-492b-a08a-43e964a3c0a1"
type = "fix"
description = "Fixed an issue in `CrudResourceController.reconcile()` that would cause a resource without state to be created even if the resource had no state; and fixed `ResourceRegistry.delete()` not committing the updated resource with a deletion marker to the store."
author = "@NiklasRosenstein"

[[entries]]
id = "55409234-dc7f-468b-8035-4025b1cc0bac"
type = "feature"
description = "Add `Signature` type, remove `RulesGraph.reduce()` but add `RulesGraph.find_path()`"
author = "@NiklasRosenstein"

[[entries]]
id = "b579594b-ad1f-4d23-8aae-262e71f331ac"
type = "breaking change"
description = "Rename `equilibrium.core` to `equilibrium.resource`"
author = "@NiklasRosenstein"

[[entries]]
id = "c5e4305a-881a-4c57-8fe3-9947a2c0949a"
type = "breaking change"
description = "Rename `Context` to `ResourceContext`"
author = "@NiklasRosenstein"

[[entries]]
id = "46a5af23-3218-4f1f-9590-3c4681619d44"
type = "fix"
description = "`collect_rules()` no longer returns a generator, because that messes up the result of `inspect.stack()`"
author = "@NiklasRosenstein"

[[entries]]
id = "463c2d9d-81fa-4812-a8dd-864eeffa34af"
type = "breaking change"
description = "`Resource.URI` string representation without namespace now requires an empty string for the namespace (e.g. `apiVersion/kind//name`)"
author = "@NiklasRosenstein"

[[entries]]
id = "ee5fcf34-649c-4028-8634-31a577f90c07"
type = "improvement"
description = "`ResourceRegistry.get()` and `ServiceRegistry.get()` now have overloads that raise if no default is supplied."
author = "@NiklasRosenstein"

[[entries]]
id = "0da1df08-8da4-4604-b859-9692a47f94f4"
type = "feature"
description = "Make `Resource.URI` orderable"
author = "@NiklasRosenstein"

[[entries]]
id = "b4fc42d9-8ba0-44f9-9ac2-61d30753ec97"
type = "feature"
description = "add `ResourceRegistry.put(stateful)` parameter"
author = "@NiklasRosenstein"

[[entries]]
id = "c8c21750-ed20-4ec0-8143-97fec3655c7b"
type = "breaking change"
description = "Rename `equilibrium.rulesengine` to `equilibrium.rules`"
author = "@NiklasRosenstein"

[[entries]]
id = "33cd2799-40d4-40e2-b0af-c188c342e741"
type = "feature"
description = "`Params()` constructor now accepts a mapping that allows passing explicit runtime type information with a parameter. It now accepts instances of parameterizable generic types only if the runtime type information is given."
author = "@NiklasRosenstein"
