[[entries]]
id = "ce10bbc3-8d63-4e64-b7c0-6eb249de3105"
type = "breaking change"
description = "Rework `Context` class, make it a composite of various registries (i.e. `ControllerRegistry`, `ResourceTypeRegistry`, `ServiceRegistry` and `ResourceRegistry`"
author = "@NiklasRosenstein"
