name: Python application

on:
  push: { branches: [ main ], tags: [ "*" ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.x" ]
    steps:
    - uses: actions/checkout@v3
    - uses: python-slap/slap-cli@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install -vv --no-venv-check
    - run: slap test

  update-changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: python-slap/slap-cli@gha/changelog/update/v1
